version: '3'
services:
  downtorrent_server_dev:
    container_name: downtorrent_server_dev
    build:
      context: .
      dockerfile: Dockerfile-server.dev
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    expose:
      - "10002"
      - "51413"
    ports:
      - "10002:10002"
  downtorrent_client_dev:
    container_name: downtorrent_client_dev
    build:
      context: .
      dockerfile: Dockerfile-client.dev
    environment:
      - BACKEND_PORT=10002
      - BACKEND_URL_CORDOVA="http://danigarcia-dev.com"
    volumes:
      - ./client:/usr/src/app
    expose:
      - "10004"
    ports:
      - "10004:10004"
