version: '3'
services:
  downtorrent_back:
    container_name: downtorrent_back
    build:
      context: .
      dockerfile: Dockerfile-back
    expose:
      - "10005"
      - "9090"
      - "51413"
    ports:
      - "10005:10005"
      - "9090:9090"
  downtorrent_front:
    container_name: downtorrent_front
    build:
      context: .
      dockerfile: Dockerfile-front
    expose:
      - "80"
    ports:
      - "10003:80"
