version: '3'
services:
  downtorrent_server_prod:
    container_name: downtorrent_server_prod
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-server.prod
    expose:
      - "10003"
      - "9090"
      - "51413"
    ports:
      - "10003:10003"
      - "9090:9090"
  downtorrent_client_prod:
    container_name: downtorrent_client_prod
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-client.prod
    expose:
      - "80"
    ports:
      - "10005:80"
